### ISSUE TITLE
neaten up!

### ISSUE THREAD

**Issue by ladyada** [adafruit/Adafruit_CircuitPython_MMC56x3#2]
@tekktrik here's another library with working code but needs CI ❤️

**Comment by tekktrik** [comment]
Got it!

**Comment by tekktrik** [comment]
All set to go!  Even threw in type annotations real quick.  Once I can add libraries to RTD I'll do the same for this and close this.

**Comment by ladyada** [comment]
oh also please submit to pypi (this and the other library PCF8574)

**Comment by tekktrik** [comment]
@kattni This library is ready for PyPI!  Everything else is set.

**Comment by kattni** [comment]
RTD setup completed.
